# Generated by Django 6.1.1 on 2026-09-28 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('due_date', models.DateField()),
                ('recurrence', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('verified', 'Verified')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chores', to='chores.member')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.household')),
            ],
            options={
                'ordering': ['due_date', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='chore_points_positive'), models.CheckConstraint(condition=models.Q(('recurrence__in', ['once', 'daily', 'weekly', 'monthly'])), name='chore_recurrence_valid')],
            },
        ),
    ]
